# Generated by Django 4.1.5 on 2023-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0032_studroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mailid', models.DateField(max_length=100)),
                ('country', models.TimeField(max_length=100)),
                ('subject', models.TimeField(max_length=100)),
            ],
        ),
    ]
