# Generated by Django 4.1.5 on 2023-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0033_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mailid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
