# Generated by Django 4.1.5 on 2023-02-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0034_alter_feedback_country_alter_feedback_mailid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='mailid',
            new_name='email',
        ),
    ]
