# Generated by Django 4.1.5 on 2023-02-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0035_rename_mailid_feedback_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='lastname',
            new_name='ln',
        ),
    ]
