# Generated by Django 4.1.5 on 2023-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0036_rename_lastname_feedback_ln'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roomno', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('MaxPerson', models.CharField(max_length=100)),
            ],
        ),
    ]
