# Generated by Django 4.1.5 on 2023-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0037_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldetail',
            name='mobile',
            field=models.IntegerField(max_length=200),
        ),
    ]
