# Generated by Django 4.1.5 on 2023-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0038_alter_hosteldetail_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Fathername', models.CharField(max_length=100)),
                ('Mothername', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Fatheroccupation', models.CharField(max_length=100)),
                ('Fathernumber', models.CharField(max_length=100)),
                ('Studentnumber', models.CharField(max_length=100)),
            ],
        ),
    ]
