# Generated by Django 4.1.5 on 2023-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0040_selectroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='Roomno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
